/* Data & KPI Lab content.
   Two groups, each with its own index + detail pages:
   1) STANDARD ("Advanced Data & KPIs for Variation Theory") — established metrics jin applies.
   2) LAB ("Data & KPI Lab") — KPIs jin designed / re-applied to measure Variation directly.
      status + type mirror wiki/synthesis/jin_kpi_lab.md. Edit freely. */

export type Standard = {
  id: string;
  abbr: string;
  name: string;
  short: string;      // card blurb (interest hook)
  measures: string;   // what it measures
  question: string;   // the tactical question it answers
  detail: string;     // full write-up
};

export const STANDARD: Standard[] = [
  { id: "xt", abbr: "xT", name: "Expected Threat", short: "A value for every metre of progression.", measures: "How much an on-ball action raises scoring probability by moving the ball to a more dangerous zone.", question: "Where does progression actually create danger?", detail: "Expected Threat divides the pitch into zones and assigns each a probability of leading to a goal within the next few actions. Every pass or carry is then valued by the change in threat between its start and end zone. For the Variation framework it is the base currency: it lets a low-xT conditioning phase (Plan A−) and a high-xT spike (Plan A) be told apart in the data, and it is the input for the timing and sequencing KPIs in the Lab." },
  { id: "vaep", abbr: "VAEP", name: "Valuing Actions (VAEP)", short: "Every action priced at both ends.", measures: "Values every action by its effect on both scoring and conceding probability.", question: "What is each action really worth, at both ends?", detail: "VAEP estimates, for every action, how much it changes the team's probability of scoring and of conceding in the near future — then nets the two. Unlike xT it credits defensive actions too, which matters for a philosophy that treats defence as option-removal rather than an afterthought." },
  { id: "obv", abbr: "OBV", name: "On-Ball Value", short: "Which touches move the needle.", measures: "The change in a team's expected goals produced by a single on-ball action.", question: "Which individual actions move the needle?", detail: "On-Ball Value attributes the swing in expected goals to the player performing each on-ball action. It is useful for spotting the individuals who generate variation — the ones whose receptions and carries repeatedly shift the danger level rather than merely recycle possession." },
  { id: "epv", abbr: "EPV", name: "Expected Possession Value", short: "How much this moment is worth.", measures: "The value of the current possession state before the next action is taken.", question: "How valuable is this moment on the pitch?", detail: "EPV values the state of a possession — position, players, pressure — as a live expected-goals figure, before any action is chosen. Reading EPV across a sequence shows how a possession is being built, and where a variation suddenly lifts the value the opponent thought they had contained." },
  { id: "psxg", abbr: "PSxG", name: "Post-Shot xG", short: "Shot quality after the strike.", measures: "Shot quality after the strike, factoring in placement and contact.", question: "Finishing and shot-stopping over/under-performance.", detail: "Post-Shot xG re-values a shot once it has been struck, using placement and contact. The gap between xG and PSxG isolates finishing quality; the gap between PSxG and goals isolates goalkeeping. It keeps the analysis honest about how much of a scoreline was chance creation versus execution." },
  { id: "field-tilt", abbr: "FT", name: "Field Tilt", short: "Who owns the dangerous third.", measures: "A team's share of final-third possession — territorial dominance.", question: "Who controls the dangerous third?", detail: "Field Tilt is the share of final-third possession between the two teams — a cleaner read of territorial control than raw possession. In the framework it tracks whether a conditioning phase is actually pinning the opponent, which is the precondition for a Lure that means anything." },
  { id: "ppda", abbr: "PPDA", name: "Passes per Defensive Action", short: "How hard the team hunts the ball.", measures: "Opponent passes allowed per defensive action in their build-up zone.", question: "How aggressively does the team press?", detail: "PPDA counts how many passes the opponent is allowed to make per defensive action in their build-up area — a low number means aggressive pressing. It quantifies Phase 1 of the defensive model (the seven-second gegenpress window) and is later re-applied, from the attacking side, in the Lab's Reverse PPDA." },
  { id: "forced-turnover", abbr: "FTO", name: "Forced Turnover", short: "The springboard for transition.", measures: "Turnovers won through active defensive pressure.", question: "Does the defence create the springboard for transition?", detail: "Forced Turnovers count possessions won through active pressure rather than passive interception. For a direct-transition side they are the ignition point of an attack, and they connect the defensive phase to the very first frame of a Plan A spike." },
  { id: "progressive", abbr: "PP", name: "Progressive Pass / Carry", short: "Who drives the ball forward.", measures: "Passes and carries that move the ball meaningfully toward goal.", question: "Who drives progression — and how?", detail: "Progressive passes and carries flag the actions that meaningfully advance the ball toward goal. Splitting progression by pass versus carry, and by player, reveals whether a team advances through structure or through individuals leaving their line — the raw material of mutation." },
  { id: "rft", abbr: "RFT", name: "Receptions in Final Third", short: "Who arrives where it hurts.", measures: "Receiving the ball inside the final third.", question: "Who gets the ball into dangerous receiving zones?", detail: "Receptions in the Final Third count how often, and by whom, the ball is received in the danger area. It is the destination half of the Lab's DLB → RFT conversion metric: breaking a line only matters if someone actually receives beyond it." },
  { id: "dlb", abbr: "DLB", name: "Defensive Line Break", short: "Does build-up actually pierce?", measures: "Actions that break through the opponent's defensive line.", question: "Does build-up actually penetrate the block?", detail: "A Defensive Line Break is an action that plays through or past a line of the opponent's block. Counting them separates possession that circulates in front of the block from possession that genuinely penetrates it — the moment a variation converts into territory." },
  { id: "pass-network", abbr: "PN", name: "Pass Network", short: "The team's true shape.", measures: "The map of pass connections and average positions.", question: "What is the team's real shape, and who connects it?", detail: "A pass network plots average positions and the strength of connections between them, exposing a team's real in-possession shape versus its nominal formation. Its dispersion over a season is the basis for one of the Lab's multi-season trend KPIs — a more distributed network is harder to pre-scout." },
];

export type LabType = "Combination" | "Re-application" | "Theory-derived";
export type LabStatus = "concept" | "draft" | "live";

export type LabKpi = {
  id: string;
  code: string;
  name: string;
  type: LabType;
  status: LabStatus;
  short: string;   // card blurb
  detail: string;  // full write-up
  /** The existing KPI(s)/data (STANDARD abbrs, or raw data source) this concept is built from or measured with — shown as tags on the index card. */
  basedOn: string[];
};

export const LAB: LabKpi[] = [
  { id: "dlb-rft", code: "2-2", name: "DLB → RFT Conversion", type: "Combination", status: "draft", short: "Does a line-break actually reach a dangerous reception?", basedOn: ["DLB", "RFT"], detail: "The share of defensive line-breaks (DLB) that lead to a final-third reception (RFT) within a few seconds — a measure of whether a Plan A transition carries all the way to the finish rather than stalling. Draft definition: (DLBs that lead to an RFT) / (total DLBs), with the connecting window still to be fixed (5s? same possession?). Measurable from basic video tagging; next step is establishing a benchmark from real matches." },
  { id: "xt-spike-timing", code: "2-3", name: "xT Spike-Timing Deviation", type: "Re-application", status: "draft", short: "Can the opponent predict when the danger lands?", basedOn: ["xT"], detail: "The variance in *when*, inside a possession, high-xT actions occur. Variation says the opponent must not be able to predict the moment of the spike — so a larger spread of spike timings is the goal. Draft method: record the timestamp of each above-threshold xT action, then take the standard deviation across possessions. Needs raw event data with timestamps and a Python/R script to compute." },
  { id: "reverse-ppda", code: "3-2", name: "Reverse PPDA", type: "Re-application", status: "draft", short: "PPDA read from the attacking side.", basedOn: ["PPDA"], detail: "PPDA re-applied from the perspective of the team in possession — how the opponent's press is baited, drawn in, and then broken. It reframes a defensive-pressure metric as a measure of how effectively a build-up lures pressure before releasing through it. Still needs supporting use-cases and literature." },
  { id: "channel-entropy", code: "E-2", name: "Attacking-Channel Entropy", type: "Theory-derived", status: "draft", short: "How evenly unpredictable are the attacking channels?", basedOn: ["PP"], detail: "Information entropy applied to which vertical channels an attack uses, read off progressive pass/carry (PP) corridors. A perfectly one-sided attack has low entropy; a genuinely unpredictable one spreads across channels and scores high. Derived directly from information theory; needs a normalised-entropy (H_norm) benchmark and a tagging pipeline." },
  { id: "receiver-entropy", code: "E-4", name: "Final-Third Receiver Entropy", type: "Theory-derived", status: "draft", short: "Is there a fixed reference point to defend?", basedOn: ["RFT"], detail: "Entropy applied to *who* receives in the final third (RFT). A block defends reference points; if the final-third receiver is highly unpredictable (high entropy), there is no reference point to defend — the data face of the no-fixed-position attack. Needs an H_norm benchmark and tagging pipeline." },
  { id: "match-xt-variance", code: "S-1", name: "Match xT Variance", type: "Re-application", status: "concept", short: "The low-then-spike signature, at season scale.", basedOn: ["xT"], detail: "The spread of match-level xT across a season — the statistical fingerprint of Lure & Shock played over many games (long, low-threat conditioning phases punctuated by high-threat spikes). Concept stage: needs a season-scale data-collection method." },
  { id: "plan-a-completion", code: "S-2", name: "Plan-A Completion Rate", type: "Combination", status: "concept", short: "How often does the full attacking cycle complete?", basedOn: ["DLB", "RFT"], detail: "The proportion of matches in which the complete attacking cycle actually finishes (e.g. a defined number of DLB → RFT completions). Concept stage: the definition of a 'completed' cycle still needs a threshold." },
  { id: "scoring-entropy", code: "S-3", name: "Scoring-Pattern Entropy", type: "Theory-derived", status: "concept", short: "How varied are the ways goals arrive?", basedOn: ["PSxG"], detail: "Entropy applied to goal-scoring patterns across a season, using post-shot xG (PSxG) to confirm which shots were genuine chances — a varied, high-entropy scoring profile is harder to plan against than a one-note one. Concept stage: needs a classification scheme for scoring patterns." },
  { id: "response-diversity", code: "S-4", name: "Tactical-Response Diversity", type: "Re-application", status: "concept", short: "How many answers to how many setups?", basedOn: ["PN"], detail: "The breadth of distinct responses a side shows to different opponent setups, read off how much the pass network (PN) shape shifts match to match. Hard to fully quantify, so it is designed as an observation-supported measure rather than a purely numeric one. Concept stage." },
  { id: "spike-frequency-trend", code: "M-1", name: "xT Spike-Frequency Trend", type: "Re-application", status: "concept", short: "Are the spikes getting more frequent over seasons?", basedOn: ["xT"], detail: "A multi-season trend in how often high-xT spikes are generated — evidence of whether the model's output is compounding as the squad learns it. Concept stage: needs multi-season data and correction for external variables." },
  { id: "network-dispersion-trend", code: "M-2", name: "Pass-Network Dispersion Trend", type: "Re-application", status: "concept", short: "Is the shape getting harder to pre-scout?", basedOn: ["PN"], detail: "A multi-season trend in how distributed the passing network (PN) is — a more dispersed network resists pre-scouting. Concept stage: needs multi-season data with correction for player turnover." },
  { id: "adaptation-window", code: "M-3", name: "New-Signing Adaptation Window", type: "Combination", status: "concept", short: "How fast do new players reach the system's output?", basedOn: ["VAEP"], detail: "How long a new signing takes to reach the system's variation output, tracked via their VAEP trend match to match — a measure of how teachable the model is. Concept stage: the definition of 'adapted' still needs a threshold." },

  { id: "comfort-zone-deviation", code: "C-1", name: "Comfort Zone Deviation Index", type: "Theory-derived", status: "concept", short: "How far does a player's real map stray from the position's average?", basedOn: ["PN"], detail: "A player's touch/heatmap positions compared against the season average heatmap for the same position (e.g. Modrić vs a median No. 6) — the data face of the Comfort Zone concept: a large, structured deviation is a Signature Move signature, not noise. Built on the same average-position computation that underlies Pass Network (PN), extended from team-level average positions down to individual, position-normalised deviation. Concept stage: needs a same-position benchmark population and a way to separate 'structured deviation' from randomness." },
  { id: "sm-pressure-differential", code: "C-2", name: "Signature Move Pressure Differential", type: "Theory-derived", status: "concept", short: "Does the Signature Move survive a real press?", basedOn: ["PPDA", "OBV"], detail: "A Signature Move's success rate split by the pressure it was executed under — PPDA at the moment of execution flags whether the defence was actually hunting the ball, and On-Ball Value (OBV) values whether the move still paid off once they were. A move that only fires cleanly in low press isn't a Signature Move yet, just a comfortable habit. Concept stage: needs a tagged library of Signature Move instances with PPDA and OBV attached to each." },
  { id: "mutation-sm-buffering", code: "C-3", name: "Mutation × Signature Move Double-Buffering Index", type: "Theory-derived", status: "concept", short: "What happens when a mutation and a Signature Move fire at once?", basedOn: ["VAEP", "PN"], detail: "When a positional mutation (a pass-network-detectable shape change) and a Signature Move land in the same sequence, the defence has to process two unscripted signals at once. This measures the combined decision-delay via VAEP swing — is the value spike bigger than mutation alone or a Signature Move alone would produce, i.e. do the two buffers actually stack? Concept stage: needs a tagging method for 'simultaneous' and a VAEP-swing baseline for each buffer alone." },
  { id: "spatial-entropy", code: "E-1", name: "Spatial/Movement Entropy", type: "Theory-derived", status: "concept", short: "How unpredictable is the team's positioning, full stop?", basedOn: ["PN"], detail: "Shannon entropy applied to the whole team's positional distribution over a match — not just attacking channel (E-2) or final-third receiver (E-4), the general-purpose version of the same idea. Built from the same average-position data that underlies Pass Network (PN); a low-entropy team occupies the same shape every time, a high-entropy one is what mutation is designed to produce. Concept stage: needs an H_norm benchmark for a 'typical' team shape to compare against." },
  { id: "field-tilt-xt-gap", code: "2-4", name: "Field Tilt × xT Gap", type: "Combination", status: "concept", short: "Territory without teeth, or teeth without territory?", basedOn: ["FT", "xT"], detail: "Pairs Field Tilt (FT) — share of final-third possession — against xT generated in the same window, flagging the divergence: high FT but low xT means the team owns the area but isn't threatening it; the mirror case flags a side that's dangerous without ever pinning the opponent back. Concept stage: needs a window definition (per possession? per 10-minute block?) and a threshold for what counts as a meaningful gap." },
  { id: "vaep-obv-divergence", code: "2-5", name: "VAEP–OBV Divergence", type: "Combination", status: "concept", short: "How much of a player's value is really the team's?", basedOn: ["VAEP", "OBV"], detail: "Compares VAEP (which folds in possession history — what led to the action) against On-Ball Value (OBV, which strips it out and values the action alone) for the same player. A player whose VAEP is far above their OBV is being carried by the team state around them; a player whose OBV holds up independent of VAEP is closer to a clean read of the individual variable. Concept stage: needs both metrics computed on the same event stream to be directly comparable." },
  { id: "formation-mutation-frequency", code: "3-3", name: "Formation Mutation Frequency", type: "Re-application", status: "concept", short: "How often does the shape actually change?", basedOn: ["PN"], detail: "A straight count of hybrid-formation changes per match or season, read off shifts in the team's pass network (PN) shape — an objective, paper-derived companion to the qualitative mutation concept: not just that shapes change, but how often, and whether that frequency is trending up as the model beds in. Concept stage: needs a formation-change detection threshold so PN shifts within noise aren't over-counted." },
  { id: "single-node-dependency", code: "S-5", name: "Single-Node Dependency Index", type: "Re-application", status: "concept", short: "How much does the team run through one man, this season?", basedOn: ["PN"], detail: "The single-season read of how concentrated ball circulation is on one player, via pass network (PN) betweenness centrality — the snapshot version of M-2's multi-season dispersion trend. A high dependency score names the individual variable the team actually leans on, and doubles as an early-warning signal for what an opponent should target to neutralise it. Concept stage: needs a normalised betweenness benchmark across a full squad." },
  { id: "dlb-timing-variance-season", code: "M-4", name: "Season-Scale DLB Timing Variance", type: "Re-application", status: "concept", short: "Does the team's line-break timing scatter more as the season wears on?", basedOn: ["DLB"], detail: "Tracks the variance in when Defensive Line Breaks (DLB) happen across a season — distinct from 2-3's within-possession xT-spike timing and M-1's spike-frequency trend, this is DLB-specific, and asks whether the group's shared understanding of variation timing widens (more scatter, harder to predict) as fitness and cohesion build through the season. Concept stage: needs multi-season DLB timestamps and a way to control for fixture congestion." },
];

export const STATUS_BADGE: Record<LabStatus, { label: string; color: string; bg: string; border: string }> = {
  concept: { label: "Concept", color: "#c9a24a", bg: "rgba(201,162,74,0.12)", border: "rgba(201,162,74,0.30)" },
  draft:   { label: "Draft",   color: "#5bb85b", bg: "rgba(74,166,74,0.15)",  border: "rgba(74,166,74,0.36)" },
  live:    { label: "Live",    color: "#7dff6a", bg: "rgba(125,255,106,0.14)", border: "rgba(125,255,106,0.28)" },
};

export function findStandard(id: string) { return STANDARD.find((m) => m.id === id); }
export function findLab(id: string) { return LAB.find((k) => k.id === id); }
